# .github/workflows/ci-sanity.yml
name: CI Sanity
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI is alive"
